# Generated by Django 3.1.7 on 2021-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210420_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(default='sheets', max_length=30),
            preserve_default=False,
        ),
    ]
