# Generated by Django 3.1.7 on 2021-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
    ]
