# Generated by Django 3.1.7 on 2021-05-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210430_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='company',
        ),
    ]
