# Generated by Django 3.1.7 on 2021-05-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210530_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='media',
        ),
    ]
