# Generated by Django 3.1.7 on 2021-05-30 04:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210530_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.CharBlock())], null=True),
        ),
    ]
