# Generated by Django 3.1.7 on 2021-05-31 10:03

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210530_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=wagtail.core.fields.StreamField([('video_URL', wagtail.core.blocks.CharBlock(icon='media'))], null=True),
        ),
    ]
