# Generated by Django 3.1.7 on 2021-04-11 13:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('colour', wagtail.core.blocks.CharBlock(default='primary-800', max_length=20)), ('bold', wagtail.core.blocks.BooleanBlock(required=False)), ('level', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'Heading level 2'), ('h3', 'Heading level 3'), ('h4', 'Heading level 4'), ('p', 'Paragraph')])), ('space', wagtail.core.blocks.CharBlock(default='0', help_text='Set space below text.', max_length=2))])), ('text_body', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul'], required=True)), ('colour', wagtail.core.blocks.CharBlock(default='grey-700', max_length=20)), ('leading', wagtail.core.blocks.CharBlock(default='8', help_text='Set space between lines.', max_length=2))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.core.blocks.CharBlock(required=True)), ('show_caption', wagtail.core.blocks.BooleanBlock(default=False, required=False))]))]),
        ),
    ]
