# Generated by Django 3.1.7 on 2021-04-11 13:36

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('flexible', '0003_remove_blogpostpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='flexible.BlogTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
