# Generated by Django 3.1.7 on 2021-03-31 14:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0003_auto_20210331_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_heading', models.CharField(max_length=100, null=True)),
                ('company_details', wagtail.core.fields.RichTextField(null=True)),
                ('team_heading', models.CharField(blank=True, max_length=40, null=True)),
                ('team_cards', wagtail.core.fields.StreamField([('emp_cards', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add employee name', required=True)), ('job_title', wagtail.core.blocks.CharBlock(help_text='Add job title', required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('short_bio', wagtail.core.blocks.TextBlock(help_text='Add a short bio (OPTIONAL)', required=False)), ('email', wagtail.core.blocks.EmailBlock(help_text='Add employee email id', required=False)), ('phone', wagtail.core.blocks.CharBlock(help_text='Add phone number', required=False)), ('linkedin', wagtail.core.blocks.URLBlock(help_text='Add URL for LinkedIn account', required=False))], label='Employee'))], blank=True, null=True)),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
