# Generated by Django 3.1.7 on 2021-03-31 16:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='team_cards',
            field=wagtail.core.fields.StreamField([('emp_cards', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Add employee name', required=True)), ('job_title', wagtail.core.blocks.CharBlock(help_text='Add job title', required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('short_bio', wagtail.core.blocks.TextBlock(help_text='Add a short bio (OPTIONAL)', required=False)), ('phone', wagtail.core.blocks.CharBlock(help_text='Add phone number', required=False)), ('whatsapp', wagtail.core.blocks.CharBlock(help_text='Add full phone number in international format without any zeroes, brackets, or dashes.', required=False)), ('email', wagtail.core.blocks.EmailBlock(help_text='Add employee email id', required=False)), ('linkedin', wagtail.core.blocks.URLBlock(help_text='Add URL for LinkedIn account', required=False))], label='Employee'))], blank=True, null=True),
        ),
    ]
