# Generated by Django 3.1.7 on 2021-04-01 11:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0005_auto_20210331_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, max_length=40, null=True)),
                ('facebook', models.URLField(blank=True, max_length=40, null=True)),
                ('youtube', models.URLField(blank=True, max_length=40, null=True)),
                ('instagram', models.URLField(blank=True, max_length=40, null=True)),
                ('twitter', models.URLField(blank=True, max_length=40, null=True)),
                ('addresses', wagtail.core.fields.StreamField([('address', wagtail.core.blocks.StructBlock([('address1', wagtail.core.blocks.CharBlock(required=False)), ('address2', wagtail.core.blocks.CharBlock(required=True)), ('city', wagtail.core.blocks.CharBlock(required=False)), ('state', wagtail.core.blocks.CharBlock(required=True)), ('country', wagtail.core.blocks.CharBlock(required=True)), ('pincode', wagtail.core.blocks.CharBlock(required=False)), ('email', wagtail.core.blocks.CharBlock(required=True)), ('phone1', wagtail.core.blocks.CharBlock(required=True)), ('phone2', wagtail.core.blocks.CharBlock(required=True))], label='Address'))], blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
