# Generated by Django 3.1.7 on 2021-04-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_contactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='parent_company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
