# Generated by Django 3.1.7 on 2021-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210409_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='company_name',
            new_name='brand_name',
        ),
    ]
