# Generated by Django 3.1.7 on 2021-04-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210401_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaddress',
            name='site',
        ),
    ]
