# Generated by Django 3.1.7 on 2021-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_mainmenu_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='show_when',
        ),
    ]
