# Generated by Django 3.1.7 on 2021-04-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210407_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMenu',
            new_name='Menu',
        ),
    ]
