# Generated by Django 3.1.7 on 2021-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210407_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
