# Generated by Django 3.1.7 on 2021-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_businessaddress_show_in_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddress',
            name='map_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
