# Generated by Django 3.1.7 on 2021-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_businessaddress_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='section',
            field=models.CharField(blank=True, help_text='Specify page section to link to. Leave blank to link to top of page.', max_length=20, null=True),
        ),
    ]
