# Generated by Django 3.1.7 on 2021-04-17 07:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('products', '0002_auto_20210415_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='images_and_video',
        ),
        migrations.AddField(
            model_name='productpage',
            name='additional_media',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(help_text='Add full phone number in international format without any zeroes, brackets, or dashes.', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
